server:
  port: 8082

spring:
  application:
    name: dubbo-boot-auth
dubbo:
  application:
    name: dubbo-boot-auth

  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1
    port: 2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.playwi0.ssoauth.service.impl

